flyaround_map_terrain:
    resource: "@FlyaroundMapBundle/Resources/config/routing/terrain.yml"
    prefix:   /terrain

flyaround_map_fly:
    resource: "@FlyaroundMapBundle/Resources/config/routing/fly.yml"
    prefix:   /fly

flyaround_map_homepage:
    pattern:  /app
    defaults: { _controller: FlyaroundMapBundle:Default:index }
