parameters:
#    flyaround_map.example.class: Flyaround\MapBundle\Example

services:
#    flyaround_map.example:
#        class: %flyaround_map.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
